//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはReEngineのGUIツールによって生成されました。
//     このファイルへの変更は、不正な動作の原因になったり、
//     コードが再生成されるときに損失したりしますので編集しないでください。
// </auto-generated>
//------------------------------------------------------------------------------

// [Settings]
// ExportUnusedSymbol = False
// ReferenceExternalSymbol = False
// UseGUIStringPath = False

namespace via.gui.asset
{
	public class HUDFog
	{
		// Root objects
		
		public static _Root_ Root { get { return new _Root_(1219645687); } }
		
		public static _PNL_Fog_ PNL_Fog { get { return new _PNL_Fog_(2404859977); } }
		
		// Symbol define
		public static class SymbolDef
		{
			/// <summary>[Type=via.gui.View]</summary>
			public static _Root_ Root { get { return new _Root_(); } }
			/// <summary>[Type=via.gui.Panel]</summary>
			public static _PNL_Fog_ PNL_Fog { get { return new _PNL_Fog_(); } }
		}
		
		// Symbols
		
		/// <summary>Root [Type=via.gui.View]</summary>
		public class _Root_ : via.gui.GUIHashPath<via.gui.View>
		{
			
			public _Root_() : base(){}
			public _Root_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public _PNL_Fog_ PNL_Fog { get { if (_0 == null) { create(ref _0, 2404859977); } return _0; } }
			
			public class _ParamVarDefine_
			{
				/// <summary>[Type Float3] </summary>
				public GUIParamVarDefine<via.Float3> rotation { get { return new GUIParamVarDefine<via.Float3>(131106788); } }
			}
			public _ParamVarDefine_ ParamDef { get { if (_p == null) { _p = new _ParamVarDefine_(); } return _p; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			/// <summary>無効</summary>
			public string State_DISABLE { get { return _State_DISABLE; } } 
			/// <summary>IN演出</summary>
			public string State_FADE_IN { get { return _State_FADE_IN; } } 
			/// <summary>OUT演出</summary>
			public string State_FADE_OUT { get { return _State_FADE_OUT; } } 
			
			#region field (internal)
			private _PNL_Fog_ _0;
			private _ParamVarDefine_ _p;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			private const string _State_DISABLE = "DISABLE";
			private const string _State_FADE_IN = "FADE_IN";
			private const string _State_FADE_OUT = "FADE_OUT";
			#endregion
		}
		
		/// <summary>PNL_Fog [Type=via.gui.Panel]</summary>
		public class _PNL_Fog_ : via.gui.GUIHashPath<via.gui.Panel>
		{
			
			public _PNL_Fog_() : base(){}
			public _PNL_Fog_(uint nameHash, GUIHashPath parent = null) : base(nameHash, parent){}
			
			public via.gui.GUIHashPath<via.gui.Texture> tex_HUDFog { get { if (_0 == null) { create(ref _0, 2753721660); } return _0; } }
			
			public uint Pattern_Default { get { return _Pattern_Default; } } 
			/// <summary>通常状態</summary>
			public string State_DEFAULT { get { return _State_DEFAULT; } } 
			
			#region field (internal)
			private via.gui.GUIHashPath<via.gui.Texture> _0;
			private const uint _Pattern_Default = 0;
			private const string _State_DEFAULT = "DEFAULT";
			#endregion
		}
		
		#region Legacy GUI Parameter Variable IDs (GPI)
		
		// ※ 旧仕様向けの出力です。Rootや各コントロールのParamDefクラス以下に変数定義があるのでそちらを利用してください。
		
		/// <summary>[Type Float3] </summary>
		[System.Obsolete("Root.ParamDef.rotationに書き換えてください。")]
		public static string GPI_rotation = "rotation";
		
		#endregion
		
	}
}

